[build]
  publish = "dist"
  command = "rm -rf .parcel-cache && npm run build"

[build.environment]
  NODE_VERSION = "20"
  PARCEL_WORKERS = "0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
